### ISSUE TITLE
Spinner?

### ISSUE THREAD

**Issue by yellowjaguar5** [MajikalExplosions/prototype#1]
Look here: [http://tobiasahlin.com/spinkit/](http://tobiasahlin.com/spinkit/)

**Comment by MajikalExplosions** [comment]
Uh
What for?

**Comment by yellowjaguar5** [comment]
Niles said this was going to be a game. Games often need loader gifs and these are nice ones.

**Comment by SheepTester** [comment]
No games do not need loader gifs. What games need are SVGs with CSS animations.

Or faster loading time.
